CREATE TABLE customer_ageing_prod
(
    company_code                 integer,
    customer                     varchar(255),
    customer_name                varchar(255),
    reconciliation_acct          bigint,
    gl_acct_long_text            varchar(255),
    fiscal_year                  integer,
    document_date                date,
    description                  varchar(255),
    posting_date                 date,
    due_date                     date,
    cust_reference               varchar(100),
    sales_document               varchar(50),
    billing_doc                  varchar(50),
    document_type                varchar(10),
    document_number              bigint,
    reference                    varchar(100),
    assignment                   varchar(100),
    profit_center                varchar(50),
    debit_credit                 varchar(5),
    special_gl_ind               varchar(5),
    invoice_amt                  numeric(15, 2),
    amount_in_lc                 numeric(15, 2),
    total_outstanding            numeric(15, 2),
    unadjusted_credit            numeric(15, 2),
    adv_reced                    numeric(15, 2),
    not_due_amount               numeric(15, 2),
    no_of_days_os                integer,
    tot01_30days_outstanding     numeric(15, 2),
    tot31_60days_outstanding     numeric(15, 2),
    tot61_90days_outstanding     numeric(15, 2),
    tot91_120days_outstanding    numeric(15, 2),
    tot121_180days_outstanding   numeric(15, 2),
    tot181_360days_outstanding   numeric(15, 2),
    tot361_999days_outstanding   numeric(15, 2),
    tot1000_9999days_outstanding numeric(15, 2),
    all_inclusive_amt            numeric(15, 2),
    currency                     varchar(10),
    city                         varchar(100),
    region                       varchar(50),
    country_reg                  varchar(10),
    sales_district               varchar(50),
    payt_terms                   varchar(30),
    own_explanatn                varchar(255),
    currency1                    varchar(10),
    item_descr                   varchar(255),
    doc_header_text              varchar(255),
    ship_to_party                varchar(50),
    ship_to_party_name           varchar(255),
    distr_channel                varchar(50),
    sales_office                 varchar(50),
    customer_group               varchar(50),
    sales_group                  varchar(50),
    name                         varchar(255),
    sales_group_description      varchar(255),
    "desc"                       varchar(255),
    business_area                varchar(50),
    business_area_description    varchar(255),
    last_updated_at              timestamp
);
